name: PHP tests
inputs:
  presta-versions:
    description: "PrestaShop versions to test"
    required: true
    type: string
  php-versions:
    description: "PHP versions to use"
    required: true
    type: string

runs:
  using: "composite"
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Run PHP Linter
      shell: bash  # Ajout du shell
      run: |
        IFS=',' read -r -a php_array <<< "${{ inputs.php-versions }}"
        for php_version in "${php_array[@]}"; do
          echo "Running PHP syntax checker for version $php_version"
          # Appellez ici l'action PHP linter
          echo "Using action: prestashop/github-action-php-lint/${php_version}@master"  # Pour débogage
          uses: prestashop/github-action-php-lint/${php_version}@master
        done