name: PHP tests
inputs:
  presta-versions:
    description: "PrestaShop versions to test"
    required: true
    type: string
  php-versions:
    description: "PHP versions to use"
    required: true
    type: string

runs:
  php-linter:
    name: PHP Syntax check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ${{ fromJson(inputs.php-versions) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: PHP syntax checker ${{ matrix.php-versions }}
        uses: prestashop/github-action-php-lint/${{ matrix.php-versions }}@master