name: PHP Syntax Checker
on:
  workflow_call:
    inputs:
      php-version:
        description: "PHP version to use"
        required: true
        type: string

jobs:
  php-linter:
    name: PHP Syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHP syntax checker ${{ inputs.php-version }}
        uses: prestashop/github-action-php-lint/${{ inputs.php-version }}@master